version: '3.7'

services:
  backend:
    container_name: backend
    image: backend-img
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_MONGO_HOST=${DB_MONGO_HOST}
      - DB_MONGO_USERNAME=${DB_MONGO_USERNAME}
      - DB_MONGO_PASSWORD=${DB_MONGO_PASSWORD}
      - DB_MONGO_PORT=${DB_MONGO_PORT}
      - DB_MONGO_DATABASE=${DB_MONGO_DATABASE}
    depends_on:
      - mongo
  mongo:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_MONGO_DATABASE}
